apiVersion: v1
kind: Template
labels:
  template: secret-generic-opaque
metadata:
  template: secret-generic-opaque
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${SA_NAME}"
    namespace: "${SA_NAMESPACE}"
parameters:
- description: The name of the service account that will be created
  displayName: Service Account Name
  name: SA_NAME
  required: true
- description: The namespace that the service account will be created in
  displayName: Service Account Namespace
  name: SA_NAMESPACE
  required: true
