dist: xenial
language: python
python:
  - "3.7"

before_install:
  - sudo add-apt-repository ppa:rmescandon/yq -y
  - sudo apt update -q
  - sudo apt install yq -y

script:
# Check we only have 1 extension for yml
  - find . -type f -name "*.yaml" -exec echo {} \;
  - if [[ $(find . -type f -name "*.yaml" | wc -l)  -gt 0 ]] ; then echo "Found .yaml; only expected .yml"; exit 1; fi

# Validate yml
  - find . -type f -name "*.yml" -exec echo -e "\n{}" \; -exec  yq read {} \;