---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: java-app-deploy
  annotations:
    openshift.io/display-name: Fabric8 Deploy Rolebinding
    description: A template to support the role bindings needed fabric8 k8s libraries
    iconClass: icon-cube
    tags: cube
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  groupNames:
  - system:serviceaccounts:${APP_NAMESPACE}
  metadata:
    name: view
  roleRef:
    name: view
    apiGroup: rbac.authorization.k8s.io
    kind: Role
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:${APP_NAMESPACE}
  userNames: 
parameters:
- name: APP_NAMESPACE
  displayName: Project/Namespace for the App
  description: The project/namespace where the App is deployed.
  required: true
labels:
  template: fabric8-deploy-role-bindings-template
