---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: add-role-to-group
  annotations:
    openshift.io/display-name: Group and role binding Access template
    description: RoleBinding to give access to project
labels:
  template: role-to-group-binding
objects:
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: "${GROUP}_${ROLE}_role"
  roleRef:
    name: "${ROLE}"
  subjects:
  - kind: Group
    name: "${GROUP}"
  groupNames:
  - "${GROUP}"
parameters:
- name: ROLE
  displayName: Role
  description: The role to bind to the group
  required: true
  value: edit
- name: GROUP
  displayName: Group
  description: The group to bind to the role
  required: true
