---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ServiceAccountClusterRoleBinding
  annotations:
    openshift.io/display-name: ClusterRoleBinding for ServiceAccount
objects:
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: "${CLUSTER_ROLE}-binding-${SA}-${SA_NAMESPACE}"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "${CLUSTER_ROLE}"
  subjects:
  - kind: ServiceAccount
    name: "${SA}"
    namespace: "${SA_NAMESPACE}"
parameters:
- name: CLUSTER_ROLE
  description: The cluster role
  required: true
- name: SA
  description: Serviceaccount to bind to
  required: true
- name: SA_NAMESPACE
  description: The namespace for the Serviceaccount
  required: true
