---
apiVersion: template.openshift.io/v1
kind: Template
message: |-
  The following CatalogSourceConfig has been created: ${NAME}
metadata:
  name: catalogsourceconfig-template
objects:
- apiVersion: operators.coreos.com/v1
  kind: CatalogSourceConfig
  metadata:
    name: ${NAME}
  spec:
    packages: "${OPERATORS}"
    targetNamespace: "${OPERATOR_NAMESPACE}" 
parameters:
- name: NAME
  required: true
  description: Name of the CatalogSourceConfig to create
- name: OPERATOR_NAMESPACE
  value: openshift-operators
  description: Namespace where you want the operator to be available
- name: OPERATORS
  required: true
  description: a single or comma-seperated list of operators which you want to subscribe to
