---
apiVersion: template.openshift.io/v1
kind: Template
message: |-
  The following Role has been created: ${NAME}
metadata:
  name: operatorgroup-template
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: ${NAME}
    namespace: ${TARGET_NAMESPACE}
  rules:
    - apiGroups:
        - operators.coreos.com
      resources:
        - installplans
        - subscriptions
      verbs:
        - get
        - list
        - patch
parameters:
- name: NAME
  required: true
  description: Name of the Role to create
- name: TARGET_NAMESPACE
  required: true
  description: A namespace for the Role to target
