---
apiVersion: template.openshift.io/v1
kind: Template
message: |-
  The following RoleBinding has been created: ${NAME}
metadata:
  name: rolebinding-template
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ${NAME}
    namespace: ${TARGET_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ${ROLE_NAME}
  subjects:
    - kind: ServiceAccount
      name: ${SUBJECT_NAME}
parameters:
- name: NAME
  required: true
  description: Name of the RoleBinding to create
- name: TARGET_NAMESPACE
  required: true
  description: A namespace for the RoleBinding to target
- name: SUBJECT_NAME
  required: true 
  description: A subject name for a RoleBinding 
- name: ROLE_NAME
  required: true
  description: Name of the role to bind to
