---
apiVersion: template.openshift.io/v1
kind: Template
message: |-
  The following Job has been created: ${NAME}
metadata:
  name: installplan-approver-job-template
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${NAME}
    namespace: ${TARGET_NAMESPACE}
  spec:
    template:
      spec:
        containers:
          - image: registry.redhat.io/openshift4/ose-cli:v4.4
            command:
              - /bin/bash
              - -c
              - |
                export HOME=/tmp/approver
                echo "Approving operator install.  Waiting a few seconds to make sure the InstallPlan gets created first."
                sleep $SLEEP
                oc project $NAMESPACE
                for subscription in `oc get subscriptions.operators.coreos.com -o jsonpath='{.items[0].metadata.name}'`
                do
                  echo "Processing subscription '$subscription'"
                  installplan=$(oc get subscriptions.operators.coreos.com --field-selector metadata.name=${subscription} -o jsonpath='{.items[0].status.installPlanRef.name}')
                  echo "Check installplan approved status"
                  oc get installplan $installplan -o jsonpath="{.spec.approved}"
                  if [ "`oc get installplan $installplan -o jsonpath="{.spec.approved}"`" == "false" ]; then
                    echo "Approving Subscription $subscription with install plan $installplan"
                    oc patch installplan $installplan --type=json -p='[{"op":"replace","path": "/spec/approved", "value": true}]'
                  else
                    echo "Install Plan '$installplan' already approved"
                  fi
                done
            imagePullPolicy: Always
            name: installplan-approver
            env:
            - name: SLEEP
              value: "20"
            - name: NAMESPACE
              value: ${TARGET_NAMESPACE}
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        serviceAccount: installplan-approver-job
        serviceAccountName: installplan-approver-job
        terminationGracePeriodSeconds: 30
parameters:
- name: NAME
  required: true
  description: Name of the Job to create
- name: TARGET_NAMESPACE
  required: true
  description: A namespace for the Job to target
