---
apiVersion: template.openshift.io/v1
kind: Template
message: |-
  The following OperatorGroup has been created: ${NAME}
metadata:
  name: operatorgroup-template
objects:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: ${NAME}
  spec:
    targetNamespaces: 
    - ${TARGET_NAMESPACE}
parameters:
- name: NAME
  required: true
  description: Name of the OperatorGroup to create
- name: TARGET_NAMESPACE
  required: true
  description: A namespace for the OperatorGroup to target
