---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: jenkins-pipeline-no-ocp-triggers-with-secret
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: "${NAME}"
      name: "${NAME}-pipeline"
      type: pipeline
    name: "${NAME}-pipeline"
  spec:
    runPolicy: "${RUN_POLICY}"
    source:
      contextDir: "${JENKINSFILE_CONTEXT_DIR}"
      git:
        ref: "${JENKINSFILE_SOURCE_REPOSITORY_REF}"
        uri: "${JENKINSFILE_SOURCE_REPOSITORY_URL}"
      type: Git
      sourceSecret:
        name: "${JENKINSFILE_SOURCE_SECRET}"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: "${JENKINSFILE_PATH}"
        env:
          - name: APP_NAME
            value: ${NAME}
          - name: CI_CD_NAMESPACE
            value: ${CI_CD_NAMESPACE}
          - name: DEV_NAMESPACE
            value: ${DEV_NAMESPACE}
          - name: TEST_NAMESPACE
            value: ${TEST_NAMESPACE}
          - name: STAGE_NAMESPACE
            value: ${STAGE_NAMESPACE}
          - name: PROD_NAMESPACE
            value: ${PROD_NAMESPACE}
      type: JenkinsPipeline
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
  value: s2i-app
- name: JENKINSFILE_SOURCE_REPOSITORY_URL
  displayName: Jenkinsfile Git Repository URL
  description: The URL of the repository with your Jenkinsfile.
  required: true
- name: JENKINSFILE_SOURCE_REPOSITORY_REF
  displayName: Jenkinsfile Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default (master) branch.
  value: master
- name: JENKINSFILE_CONTEXT_DIR
  displayName: Git Context Directory for Jenkinsfile
  description: Set this to the directory where the Jenkinsfile is if not using the
    default root directory
- name: JENKINSFILE_PATH
  displayName: Jenkinsfile Path
  description: The path to the Jenkinsfile
  required: true
  value: Jenkinsfile
- name: RUN_POLICY
  displayName: Run Policy
  description: Policy to control how the build runs
  value: Serial
  required: true
- name: JENKINSFILE_SOURCE_SECRET
  displayName: Secret for git repository
  description: The name of the OCP secret that has credentials for the pipeline git
    repository
  value: git-secret
- name: CI_CD_NAMESPACE
  displayName: CI CD Namespace
  description: Usually the same Namespace where Jenkins lives
- name: DEV_NAMESPACE
  displayName: Dev Environment Namespace
  description: Dev Environment Namespace
- name: TEST_NAMESPACE
  displayName: Test Environment Namespace
  description: Test Environment Namespace
- name: STAGE_NAMESPACE
  displayName: Stage Environment Namespace
  description: Stage Environment Namespace
- name: PROD_NAMESPACE
  displayName: Prod Environment Namespace
  description: Prod Environment Namespace
labels:
  template: s2i-app-build-with-secret-template
