---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: imagestream-generic
metadata:
  name: imagestream-generic
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      role: ${IMAGE_STREAM_ROLE}
    name: ${IMAGE_STREAM_NAME}
    namespace: ${IMAGE_STREAM_NAMESPACE}
  spec:
    tags:
    - from:
        kind: ${IMAGE_STREAM_TAG_FROM_KIND}
        name: ${IMAGE_STREAM_TAG_FROM_NAME}
      name: ${IMAGE_STREAM_TAG_NAME}
parameters:
- name: IMAGE_STREAM_NAME
  description: The name of the ImageStream
  displayName: ImageStream Name
  required: true
- name: IMAGE_STREAM_NAMESPACE
  description: The namespace of the ImageStream
  displayName: ImageStream Namespace
  value: openshift
- name: IMAGE_STREAM_ROLE
  description: The role of the ImageStream
  displayName: ImageStream Role (optional)
  value: generic-imagestream
- name: IMAGE_STREAM_TAG_FROM_NAME
  description: The name of the FROM ImageStream
  displayName: ImageStream Tag From Name
  required: true
- name: IMAGE_STREAM_TAG_NAME
  description: The Name of the ImageStream Tag
  displayName: ImageStream Tag Name
  value: latest
- name: IMAGE_STREAM_TAG_FROM_KIND
  description: The kind of the ImageStream
  displayName: ImageStream Tag From Kind
  value: DockerImage

