---
apiVersion: template.openshift.io/v1
kind: Template
message: |-
  The cluster htpasswd identity provider has been created
metadata:
  name: htpasswd-idp-template
objects:
- apiVersion: config.openshift.io/v1
  kind: OAuth
  metadata:
    name: cluster
  spec:
    identityProviders:
    - name: htpasswd
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: "${HTPASSWD_SECRET}"
parameters:
- name: HTPASSWD_SECRET
  description: Secret containing the htpasswd file
  required: true
