apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: ruby-example-template
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ruby-ex
    name: ruby-ex
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ruby-ex:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/openshift/ruby-ex.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ruby-22-centos7:latest
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: yb7r1wX6hUBmxcsteg_l
      type: GitHub
    - generic:
        secret: TkCAyduz3-Tec3Oi8ZpX
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ruby-ex
    name: ruby-22-centos7
  spec:
    tags:
    - from:
        kind: DockerImage
        name: centos/ruby-22-centos7:latest
      name: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ruby-ex
    name: ruby-ex
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ruby-ex
    name: ruby-ex
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ruby-ex
      deploymentconfig: ruby-ex
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ruby-ex
          deploymentconfig: ruby-ex
      spec:
        containers:
        - image: docker-registry.default.svc:5000/${NAMESPACE_BUILD}/ruby-ex:latest
          imagePullPolicy: Always
          name: ruby-ex
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ruby-ex
        from:
          kind: ImageStreamTag
          name: ruby-ex:latest
          namespace: ${NAMESPACE_BUILD}
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ruby-ex
    name: ruby
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ruby-ex
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ruby-ex
    name: ruby-ex
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ruby-ex
      deploymentconfig: ruby-ex
    sessionAffinity: None
    type: ClusterIP
parameters:
- description: NAMESPACE_BUILD
  displayName: NAMESPACE_BUILD
  name: NAMESPACE_BUILD
  required: true
