apiVersion: v1
kind: Template
metadata:
  name: pact-broker
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: pact-broker
    name: pact-broker  
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: pact-broker
    name: pact-broker
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: pact-broker:latest
    runPolicy: Serial
    source:
      contextDir: /pact_broker
      git:
        ref: master
        uri: ${GIT_REPOSITORY}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ruby:2.4
          namespace: openshift
      type: Source
    triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
parameters:
  - description: URL for pact_broker source code.
    displayName: URL for pact_broker source code
    value: https://github.com/DiUS/pact_broker-docker.git
    name: GIT_REPOSITORY
    required: true