apiVersion: v1
kind: Template
metadata:
  name: pact-broker
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: pact-broker
      name: pact-broker
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: pact-broker
      name: pact-broker
    spec:
      replicas: 1
      selector:
        app: pact-broker
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: pact-broker
            deploymentconfig: pact-broker
        spec:
          containers:
            - name: pact-broker
              image: "pactfoundation/pact-broker:latest"
              imagePullPolicy: Always
              env:
                - name: PACT_BROKER_DATABASE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: pact-broker-secrets
                - name: PACT_BROKER_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: pact-broker-secrets
                - name: PACT_BROKER_BASIC_AUTH_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: pact_broker_admin
                      name: pact-broker-secrets
                - name: PACT_BROKER_BASIC_AUTH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: pact_broker_admin_password
                      name: pact-broker-secrets
                - name: PACT_BROKER_BASIC_AUTH_READ_ONLY_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: pact_broker_user
                      name: pact-broker-secrets
                - name: PACT_BROKER_BASIC_AUTH_READ_ONLY_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: pact_broker_user_password
                      name: pact-broker-secrets
                - name: PACT_BROKER_DATABASE_HOST
                  value: postgresql-pact-broker
                - name: PACT_BROKER_DATABASE_NAME
                  value: pact_broker
                - name: PACT_BROKER_PORT
                  value: "8080"
                - name: PACT_BROKER_PUBLIC_HEARTBEAT
                  value: "true"
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /diagnostic/status/heartbeat
                  port: 8080
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              ports:
                - containerPort: 8080
                  protocol: TCP
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: pact-broker
      name: pact-broker
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: pact-broker
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: pact-broker
      name: pact-broker
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: pact-broker
        weight: 100
      wildcardPolicy: None
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgresql-pact-broker
      labels:
        app: pact-broker
    spec:
      ports:
        - name: postgresql
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        app: pact-broker
        deploymentconfig: postgresql-pact-broker
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: pact-broker
        deploymentconfig: postgresql-pact-broker
      name: postgresql-pact-broker
    spec:
      replicas: 1
      selector:
        app: pact-broker
        deploymentconfig: postgresql-pact-broker
      strategy:
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          labels:
            app: pact-broker
            deploymentconfig: postgresql-pact-broker
        spec:
          containers:
            - name: postgresql
              env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: pact-broker-secrets
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: pact-broker-secrets
                - name: POSTGRESQL_DATABASE
                  value: pact_broker
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 5432
                timeoutSeconds: 1
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: postgresql-pact-broker-data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: postgresql-pact-broker-data
              persistentVolumeClaim:
                claimName: postgresql-pact-broker-data
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              name: postgresql:9.5
              namespace: openshift
          type: ImageChange
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: pact-broker
        deploymentconfig: postgresql-pact-broker
      name: postgresql-pact-broker-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${POSTGRESQL_PERSISTENT_VOLUME_CLAIM_SIZE}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: pact-broker-secrets
      labels:
        app: pact-broker
        credential.sync.jenkins.openshift.io: "true"
    stringData:
      password: ${POSTGRESQL_PASSWORD}
      username: ${POSTGRESQL_USERNAME}
      pact_broker_admin: ${PACT_BROKER_BASIC_AUTH_USERNAME}
      pact_broker_admin_password: ${PACT_BROKER_BASIC_AUTH_PASSWORD}
      pact_broker_user: ${PACT_BROKER_BASIC_AUTH_READ_ONLY_USERNAME}
      pact_broker_user_password: ${PACT_BROKER_BASIC_AUTH_READ_ONLY_PASSWORD}
parameters:
  - description: Password for the PostgreSQL connection user.
    displayName: PostgreSQL Connection Password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: POSTGRESQL_PASSWORD
    required: true
  - description: Username for the PostgreSQL connection user.
    displayName: PostgreSQL Connection Username
    name: POSTGRESQL_USERNAME
    required: true
    value: pact_broker_user
  - name: PACT_BROKER_BASIC_AUTH_PASSWORD
    description: Password for the read write user in pact land.
    displayName: Password for the read write user in pact land
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    required: true
  - name: PACT_BROKER_BASIC_AUTH_USERNAME
    description: Username for the read write user in pact land.
    displayName: Username for the read write user in pact land
    required: true
    value: admin
  - name: PACT_BROKER_BASIC_AUTH_READ_ONLY_PASSWORD
    description: Password for the read only user in pact land.
    displayName: Password for the admin user in pact land
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    required: true
  - name: PACT_BROKER_BASIC_AUTH_READ_ONLY_USERNAME
    description: Username for the read only user in pact land.
    displayName: Username for the read only user in pact land
    required: true
    value: dev
  - description: Data volume size for the PostgreSQL.
    displayName: PostgreSQL Data Volume Size (Gi)
    name: POSTGRESQL_PERSISTENT_VOLUME_CLAIM_SIZE
    required: true
    value: 5Gi
