apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: secret-ssh-private-key-template
  credential.sync.jenkins.openshift.io: "true"
metadata:
  annotations:
    description: |-
      Secret template.
  name: secret-ssh-private-key-template
objects:
- apiVersion: v1
  data:
    ssh-privatekey: ${SSH_PRIVATE_KEY}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: ${SECRET_NAME}
  type: kubernetes.io/ssh-auth
parameters:
- description: Name of the secret
  displayName: Secret Name
  name: SECRET_NAME
  required: true
- description: The SSH Private Key
  displayName: SSH Private Key
  name: SSH_PRIVATE_KEY
  required: true
