---
kind: Template
apiVersion: v1
metadata:
  name: docker-cfg-secret
labels:
  template: docker-cfg-secret
objects:
- apiVersion: v1
  stringData:
    .dockerconfigjson: '{"auths":{"${REGISTRY_URL}":{"username":"${USERNAME}","password":"${PASSWORD}"}}}'
  kind: Secret
  metadata:
    name: "${NAME}"
  type: kubernetes.io/dockerconfigjson
parameters:
- name: NAME
  displayName: registry pull secret name
  description: registry pull secret name
  required: true
- name: REGISTRY_URL
  displayName: registry endpoint
  description: registry endpoint
  required: true
- name: USERNAME
  displayName: registry user
  description: registry user
  required: true
- name: PASSWORD
  displayName: registry password
  description: registry password
  required: true
