---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: secret-docker-cfg-stringdata
  annotations:
    openshift.io/display-name: .docker/config.json secret
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${NAME}"
  type: kubernetes.io/dockerconfigjson
  stringData: 
    .dockerconfigjson: >-
      {
        "auths": {
          "${REPO_FQDN}": {
            "auth": "${REPO_AUTH}"
          }
        }
      }
parameters:
- name: NAME
  displayName: Name
  description: The name of secret.
  required: true
- name: REPO_FQDN
  displayName: Repository FQDN
  description: FQDN for the image repository
  required: true
- name: REPO_AUTH
  displayName: Repository auth
  description: "The username:password base64 encoded. Ex 'echo -n USER:PASS | base64 -w0'"
  required: true
